### ISSUE TITLE
HTTP Error 500 on new user registration

### ISSUE THREAD

**Issue by bobsawyer** [cferdinandi/gmt-wordpress-for-web-apps#104]
When trying to register  a new user I get an HTTP error 500. The error log shows:

`[13-Jan-2017 19:37:26 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wpwebapp_get_theme_options_signups() in /home/boxleaders/public_html/wp-content/plugins/gmt-wordpress-for-web-apps-master/shortcodes/signup.php:110
Stack trace:
#0 /home/boxleaders/public_html/wp-includes/class-wp-hook.php(298): wpwebapp_create_new_user('')
#1 /home/boxleaders/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /home/boxleaders/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/boxleaders/public_html/wp-settings.php(449): do_action('init')
#4 /home/boxleaders/public_html/wp-config.php(89): require_once('/home/boxleader...')
#5 /home/boxleaders/public_html/wp-load.php(37): require_once('/home/boxleader...')
#6 /home/boxleaders/public_html/wp-blog-header.php(13): require_once('/home/boxleader...')
#7 /home/boxleaders/public_html/index.php(17): require('/home/boxleader...')
#8 {main}
  thrown in /home/boxleaders/public_html/wp-content/plugins/gmt-wordpress-for-web-apps-master/shortcodes/signup.php on line 110
`

I deactivated all other plugins, tried again, and got the same result. 
Running the most recent version of this plugin.
WordPress 4.7.1.

**Comment by cferdinandi** [comment]
Register via the signup form shoetcode or manually create a user in the WP Dashboard?

Thanks for the detailed debig info!

**Comment by bobsawyer** [comment]
Ah, sorry - register via the signup form shortcode.

**Comment by cferdinandi** [comment]
Thanks! Looks like I may forgotten to update a function name somewhere. I'll get this fixed asap.

**Comment by bobsawyer** [comment]
Excellent, thank you!

**Comment by cferdinandi** [comment]
Hi, this should be fixed with https://github.com/cferdinandi/gmt-wordpress-for-web-apps/pull/105

**Comment by bobsawyer** [comment]
Thanks Chris!
